### PR TITLE
Hero

### PR DESCRIPTION
**Pull request by brenancorcoran**

### CODE REVIEW

**Review by brenancorcoran — COMMENTED** [review]
lgtm!

**Review by brenancorcoran — COMMENTED** [review]
okay, now it looks good to me! haha

**Comment by brenancorcoran** [comment]
Having trouble merging this one, we will have to get some help from Ali I think

**Review by brenancorcoran — COMMENTED** [review]
lgtm (finally haha)

**Review by dsblanes — APPROVED** [review]
these look like the latest and greatest.

**Pull request merged**
